export interface CountryData {
  name: string;
  code: string; // Dialing code, e.g. '+91'
  flag: string; // Emoji, e.g. '🇮🇳'
  short: string; // ISO 2-letter code, e.g. 'IN'
}

export const COUNTRIES: CountryData[] = [
  { name: 'Afghanistan', flag: '🇦🇫', short: 'AF', code: '+93' },
  { name: 'Åland Islands', flag: '🇦🇽', short: 'AX', code: '+358' },
  { name: 'Albania', flag: '🇦🇱', short: 'AL', code: '+355' },
  { name: 'Algeria', flag: '🇩🇿', short: 'DZ', code: '+213' },
  { name: 'American Samoa', flag: '🇦🇸', short: 'AS', code: '+1684' },
  { name: 'Andorra', flag: '🇦🇩', short: 'AD', code: '+376' },
  { name: 'Angola', flag: '🇦🇴', short: 'AO', code: '+244' },
  { name: 'Anguilla', flag: '🇦🇮', short: 'AI', code: '+1264' },
  { name: 'Antarctica', flag: '🇦🇶', short: 'AQ', code: '+672' },
  { name: 'Antigua and Barbuda', flag: '🇦🇬', short: 'AG', code: '+1268' },
  { name: 'Argentina', flag: '🇦🇷', short: 'AR', code: '+54' },
  { name: 'Armenia', flag: '🇦🇲', short: 'AM', code: '+374' },
  { name: 'Aruba', flag: '🇦🇼', short: 'AW', code: '+297' },
  { name: 'Australia', flag: '🇦🇺', short: 'AU', code: '+61' },
  { name: 'Austria', flag: '🇦🇹', short: 'AT', code: '+43' },
  { name: 'Azerbaijan', flag: '🇦🇿', short: 'AZ', code: '+994' },
  { name: 'Bahamas', flag: '🇧🇸', short: 'BS', code: '+1242' },
  { name: 'Bahrain', flag: '🇧🇭', short: 'BH', code: '+973' },
  { name: 'Bangladesh', flag: '🇧🇩', short: 'BD', code: '+880' },
  { name: 'Barbados', flag: '🇧🇧', short: 'BB', code: '+1246' },
  { name: 'Belarus', flag: '🇧🇾', short: 'BY', code: '+375' },
  { name: 'Belgium', flag: '🇧🇪', short: 'BE', code: '+32' },
  { name: 'Belize', flag: '🇧🇿', short: 'BZ', code: '+501' },
  { name: 'Benin', flag: '🇧🇯', short: 'BJ', code: '+229' },
  { name: 'Bermuda', flag: '🇧🇲', short: 'BM', code: '+1441' },
  { name: 'Bhutan', flag: '🇧🇹', short: 'BT', code: '+975' },
  { name: 'Bolivia', flag: '🇧🇴', short: 'BO', code: '+591' },
  { name: 'Bosnia and Herzegovina', flag: '🇧🇦', short: 'BA', code: '+387' },
  { name: 'Botswana', flag: '🇧🇼', short: 'BW', code: '+267' },
  { name: 'Bouvet Island', flag: '🇧🇻', short: 'BV', code: '+47' },
  { name: 'Brazil', flag: '🇧🇷', short: 'BR', code: '+55' },
  { name: 'British Indian Ocean Territory', flag: '🇮🇴', short: 'IO', code: '+246' },
  { name: 'Brunei Darussalam', flag: '🇧🇳', short: 'BN', code: '+673' },
  { name: 'Bulgaria', flag: '🇧🇬', short: 'BG', code: '+359' },
  { name: 'Burkina Faso', flag: '🇧🇫', short: 'BF', code: '+226' },
  { name: 'Burundi', flag: '🇧🇮', short: 'BI', code: '+257' },
  { name: 'Cambodia', flag: '🇰🇭', short: 'KH', code: '+855' },
  { name: 'Cameroon', flag: '🇨🇲', short: 'CM', code: '+237' },
  { name: 'Canada', flag: '🇨🇦', short: 'CA', code: '+1' },
  { name: 'Cape Verde', flag: '🇨🇻', short: 'CV', code: '+238' },
  { name: 'Cayman Islands', flag: '🇰🇾', short: 'KY', code: '+1345' },
  { name: 'Central African Republic', flag: '🇨🇫', short: 'CF', code: '+236' },
  { name: 'Chad', flag: '🇹🇩', short: 'TD', code: '+235' },
  { name: 'Chile', flag: '🇨🇱', short: 'CL', code: '+56' },
  { name: 'China', flag: '🇨🇳', short: 'CN', code: '+86' },
  { name: 'Christmas Island', flag: '🇨🇽', short: 'CX', code: '+61' },
  { name: 'Cocos (Keeling) Islands', flag: '🇨🇨', short: 'CC', code: '+61' },
  { name: 'Colombia', flag: '🇨🇴', short: 'CO', code: '+57' },
  { name: 'Comoros', flag: '🇰🇲', short: 'KM', code: '+269' },
  { name: 'Congo', flag: '🇨🇬', short: 'CG', code: '+242' },
  { name: 'Congo, Democratic Republic', flag: '🇨🇩', short: 'CD', code: '+243' },
  { name: 'Cook Islands', flag: '🇨🇰', short: 'CK', code: '+682' },
  { name: 'Costa Rica', flag: '🇨🇷', short: 'CR', code: '+506' },
  { name: 'Côte d\'Ivoire', flag: '🇨🇮', short: 'CI', code: '+225' },
  { name: 'Croatia', flag: '🇭🇷', short: 'HR', code: '+385' },
  { name: 'Cuba', flag: '🇨🇺', short: 'CU', code: '+53' },
  { name: 'Cyprus', flag: '🇨🇾', short: 'CY', code: '+357' },
  { name: 'Czech Republic', flag: '🇨🇿', short: 'CZ', code: '+420' },
  { name: 'Denmark', flag: '🇩🇰', short: 'DK', code: '+45' },
  { name: 'Djibouti', flag: '🇩🇯', short: 'DJ', code: '+253' },
  { name: 'Dominica', flag: '🇩🇲', short: 'DM', code: '+1767' },
  { name: 'Dominican Republic', flag: '🇩🇴', short: 'DO', code: '+1849' },
  { name: 'Ecuador', flag: '🇪🇨', short: 'EC', code: '+593' },
  { name: 'Egypt', flag: '🇪🇬', short: 'EG', code: '+20' },
  { name: 'El Salvador', flag: '🇸🇻', short: 'SV', code: '+503' },
  { name: 'Equatorial Guinea', flag: '🇬🇶', short: 'GQ', code: '+240' },
  { name: 'Eritrea', flag: '🇪🇷', short: 'ER', code: '+291' },
  { name: 'Estonia', flag: '🇪🇪', short: 'EE', code: '+372' },
  { name: 'Ethiopia', flag: '🇪🇹', short: 'ET', code: '+251' },
  { name: 'Falkland Islands', flag: '🇫🇰', short: 'FK', code: '+500' },
  { name: 'Faroe Islands', flag: '🇫🇴', short: 'FO', code: '+298' },
  { name: 'Fiji', flag: '🇫🇯', short: 'FJ', code: '+679' },
  { name: 'Finland', flag: '🇫🇮', short: 'FI', code: '+358' },
  { name: 'France', flag: '🇫🇷', short: 'FR', code: '+33' },
  { name: 'French Guiana', flag: '🇬🇫', short: 'GF', code: '+594' },
  { name: 'French Polynesia', flag: '🇵🇫', short: 'PF', code: '+689' },
  { name: 'French Southern Territories', flag: '🇹🇫', short: 'TF', code: '+262' },
  { name: 'Gabon', flag: '🇬🇦', short: 'GA', code: '+241' },
  { name: 'Gambia', flag: '🇬🇲', short: 'GM', code: '+220' },
  { name: 'Georgia', flag: '🇬🇪', short: 'GE', code: '+995' },
  { name: 'Germany', flag: '🇩🇪', short: 'DE', code: '+49' },
  { name: 'Ghana', flag: '🇬🇭', short: 'GH', code: '+233' },
  { name: 'Gibraltar', flag: '🇬🇮', short: 'GI', code: '+350' },
  { name: 'Greece', flag: '🇬🇷', short: 'GR', code: '+30' },
  { name: 'Greenland', flag: '🇬🇱', short: 'GL', code: '+299' },
  { name: 'Grenada', flag: '🇬🇩', short: 'GD', code: '+1473' },
  { name: 'Guadeloupe', flag: '🇬🇵', short: 'GP', code: '+590' },
  { name: 'Guam', flag: '🇬🇺', short: 'GU', code: '+1671' },
  { name: 'Guatemala', flag: '🇬🇹', short: 'GT', code: '+502' },
  { name: 'Guernsey', flag: '🇬🇬', short: 'GG', code: '+44' },
  { name: 'Guinea', flag: '🇬🇳', short: 'GN', code: '+224' },
  { name: 'Guinea-Bissau', flag: '🇬🇼', short: 'GW', code: '+245' },
  { name: 'Guyana', flag: '🇬🇾', short: 'GY', code: '+592' },
  { name: 'Haiti', flag: '🇭🇹', short: 'HT', code: '+509' },
  { name: 'Heard & Mcdonald Islands', flag: '🇭🇲', short: 'HM', code: '+672' },
  { name: 'Holy See (Vatican City)', flag: '🇻🇦', short: 'VA', code: '+379' },
  { name: 'Honduras', flag: '🇭🇳', short: 'HN', code: '+504' },
  { name: 'Hong Kong', flag: '🇭🇰', short: 'HK', code: '+852' },
  { name: 'Hungary', flag: '🇭🇺', short: 'HU', code: '+36' },
  { name: 'Iceland', flag: '🇮🇸', short: 'IS', code: '+354' },
  { name: 'India', flag: '🇮🇳', short: 'IN', code: '+91' },
  { name: 'Indonesia', flag: '🇮🇩', short: 'ID', code: '+62' },
  { name: 'Iran', flag: '🇮🇷', short: 'IR', code: '+98' },
  { name: 'Iraq', flag: '🇮🇶', short: 'IQ', code: '+964' },
  { name: 'Ireland', flag: '🇮🇪', short: 'IE', code: '+353' },
  { name: 'Isle of Man', flag: '🇮🇲', short: 'IM', code: '+44' },
  { name: 'Israel', flag: '🇮🇱', short: 'IL', code: '+972' },
  { name: 'Italy', flag: '🇮🇹', short: 'IT', code: '+39' },
  { name: 'Jamaica', flag: '🇯🇲', short: 'JM', code: '+1876' },
  { name: 'Japan', flag: '🇯🇵', short: 'JP', code: '+81' },
  { name: 'Jersey', flag: '🇯🇪', short: 'JE', code: '+44' },
  { name: 'Jordan', flag: '🇯🇴', short: 'JO', code: '+962' },
  { name: 'Kazakhstan', flag: '🇰🇿', short: 'KZ', code: '+7' },
  { name: 'Kenya', flag: '🇰🇪', short: 'KE', code: '+254' },
  { name: 'Kiribati', flag: '🇰🇮', short: 'KI', code: '+686' },
  { name: 'North Korea', flag: '🇰🇵', short: 'KP', code: '+850' },
  { name: 'South Korea', flag: '🇰🇷', short: 'KR', code: '+82' },
  { name: 'Kosovo', flag: '🇽🇰', short: 'XK', code: '+383' },
  { name: 'Kuwait', flag: '🇰🇼', short: 'KW', code: '+965' },
  { name: 'Kyrgyzstan', flag: '🇰🇬', short: 'KG', code: '+996' },
  { name: 'Laos', flag: '🇱🇦', short: 'LA', code: '+856' },
  { name: 'Latvia', flag: '🇱🇻', short: 'LV', code: '+371' },
  { name: 'Lebanon', flag: '🇱🇧', short: 'LB', code: '+961' },
  { name: 'Lesotho', flag: '🇱🇸', short: 'LS', code: '+266' },
  { name: 'Liberia', flag: '🇱🇷', short: 'LR', code: '+231' },
  { name: 'Libya', flag: '🇱🇾', short: 'LY', code: '+218' },
  { name: 'Liechtenstein', flag: '🇱🇮', short: 'LI', code: '+423' },
  { name: 'Lithuania', flag: '🇱🇹', short: 'LT', code: '+370' },
  { name: 'Luxembourg', flag: '🇱🇺', short: 'LU', code: '+352' },
  { name: 'Macao', flag: '🇲🇴', short: 'MO', code: '+853' },
  { name: 'Macedonia', flag: '🇲🇰', short: 'MK', code: '+389' },
  { name: 'Madagascar', flag: '🇲🇬', short: 'MG', code: '+261' },
  { name: 'Malawi', flag: '🇲🇼', short: 'MW', code: '+265' },
  { name: 'Malaysia', flag: '🇲🇾', short: 'MY', code: '+60' },
  { name: 'Maldives', flag: '🇲🇻', short: 'MV', code: '+960' },
  { name: 'Mali', flag: '🇲🇱', short: 'ML', code: '+223' },
  { name: 'Malta', flag: '🇲🇹', short: 'MT', code: '+356' },
  { name: 'Marshall Islands', flag: '🇲🇭', short: 'MH', code: '+692' },
  { name: 'Martinique', flag: '🇲🇶', short: 'MQ', code: '+596' },
  { name: 'Mauritania', flag: '🇲🇷', short: 'MR', code: '+222' },
  { name: 'Mauritius', flag: '🇲🇺', short: 'MU', code: '+230' },
  { name: 'Mayotte', flag: '🇾🇹', short: 'YT', code: '+262' },
  { name: 'Mexico', flag: '🇲🇽', short: 'MX', code: '+52' },
  { name: 'Micronesia', flag: '🇫🇲', short: 'FM', code: '+691' },
  { name: 'Moldova', flag: '🇲🇩', short: 'MD', code: '+373' },
  { name: 'Monaco', flag: '🇲🇨', short: 'MC', code: '+377' },
  { name: 'Mongolia', flag: '🇲🇳', short: 'MN', code: '+976' },
  { name: 'Montenegro', flag: '🇲🇪', short: 'ME', code: '+382' },
  { name: 'Montserrat', flag: '🇲🇸', short: 'MS', code: '+1664' },
  { name: 'Morocco', flag: '🇲🇦', short: 'MA', code: '+212' },
  { name: 'Mozambique', flag: '🇲🇿', short: 'MZ', code: '+258' },
  { name: 'Myanmar', flag: '🇲🇲', short: 'MM', code: '+95' },
  { name: 'Namibia', flag: '🇳🇦', short: 'NA', code: '+264' },
  { name: 'Nauru', flag: '🇳🇷', short: 'NR', code: '+674' },
  { name: 'Nepal', flag: '🇳🇵', short: 'NP', code: '+977' },
  { name: 'Netherlands', flag: '🇳🇱', short: 'NL', code: '+31' },
  { name: 'New Caledonia', flag: '🇳🇨', short: 'NC', code: '+687' },
  { name: 'New Zealand', flag: '🇳🇿', short: 'NZ', code: '+64' },
  { name: 'Nicaragua', flag: '🇳🇮', short: 'NI', code: '+505' },
  { name: 'Niger', flag: '🇳🇪', short: 'NE', code: '+227' },
  { name: 'Nigeria', flag: '🇳🇬', short: 'NG', code: '+234' },
  { name: 'Niue', flag: '🇳🇺', short: 'NU', code: '+683' },
  { name: 'Norfolk Island', flag: '🇳🇫', short: 'NF', code: '+672' },
  { name: 'Northern Mariana Islands', flag: '🇲🇵', short: 'MP', code: '+1670' },
  { name: 'Norway', flag: '🇳🇴', short: 'NO', code: '+47' },
  { name: 'Oman', flag: '🇴🇲', short: 'OM', code: '+968' },
  { name: 'Pakistan', flag: '🇵🇰', short: 'PK', code: '+92' },
  { name: 'Palau', flag: '🇵🇼', short: 'PW', code: '+680' },
  { name: 'Palestine', flag: '🇵🇸', short: 'PS', code: '+970' },
  { name: 'Panama', flag: '🇵🇦', short: 'PA', code: '+507' },
  { name: 'Papua New Guinea', flag: '🇵🇬', short: 'PG', code: '+675' },
  { name: 'Paraguay', flag: '🇵🇾', short: 'PY', code: '+595' },
  { name: 'Peru', flag: '🇵🇪', short: 'PE', code: '+51' },
  { name: 'Philippines', flag: '🇵🇭', short: 'PH', code: '+63' },
  { name: 'Pitcairn', flag: '🇵🇳', short: 'PN', code: '+64' },
  { name: 'Poland', flag: '🇵🇱', short: 'PL', code: '+48' },
  { name: 'Portugal', flag: '🇵🇹', short: 'PT', code: '+351' },
  { name: 'Puerto Rico', flag: '🇵🇷', short: 'PR', code: '+1939' },
  { name: 'Qatar', flag: '🇶🇦', short: 'QA', code: '+974' },
  { name: 'Romania', flag: '🇷🇴', short: 'RO', code: '+40' },
  { name: 'Russia', flag: '🇷🇺', short: 'RU', code: '+7' },
  { name: 'Rwanda', flag: '🇷🇼', short: 'RW', code: '+250' },
  { name: 'Reunion', flag: '🇷🇪', short: 'RE', code: '+262' },
  { name: 'Saint Barthelemy', flag: '🇧🇱', short: 'BL', code: '+590' },
  { name: 'Saint Helena', flag: '🇸🇭', short: 'SH', code: '+290' },
  { name: 'Saint Kitts & Nevis', flag: '🇰🇳', short: 'KN', code: '+1869' },
  { name: 'Saint Lucia', flag: '🇱🇨', short: 'LC', code: '+1758' },
  { name: 'Saint Martin', flag: '🇲🇫', short: 'MF', code: '+590' },
  { name: 'Saint Pierre', flag: '🇵🇲', short: 'PM', code: '+508' },
  { name: 'Saint Vincent', flag: '🇻🇨', short: 'VC', code: '+1784' },
  { name: 'Samoa', flag: '🇼🇸', short: 'WS', code: '+685' },
  { name: 'San Marino', flag: '🇸🇲', short: 'SM', code: '+378' },
  { name: 'Sao Tome & Principe', flag: '🇸🇹', short: 'ST', code: '+239' },
  { name: 'Saudi Arabia', flag: '🇸🇦', short: 'SA', code: '+966' },
  { name: 'Senegal', flag: '🇸🇳', short: 'SN', code: '+221' },
  { name: 'Serbia', flag: '🇷🇸', short: 'RS', code: '+381' },
  { name: 'Seychelles', flag: '🇸🇨', short: 'SC', code: '+248' },
  { name: 'Sierra Leone', flag: '🇸🇱', short: 'SL', code: '+232' },
  { name: 'Singapore', flag: '🇸🇬', short: 'SG', code: '+65' },
  { name: 'Slovakia', flag: '🇸🇰', short: 'SK', code: '+421' },
  { name: 'Slovenia', flag: '🇸🇮', short: 'SI', code: '+386' },
  { name: 'Solomon Islands', flag: '🇸🇧', short: 'SB', code: '+677' },
  { name: 'Somalia', flag: '🇸🇴', short: 'SO', code: '+252' },
  { name: 'South Africa', flag: '🇿🇦', short: 'ZA', code: '+27' },
  { name: 'South Sudan', flag: '🇸🇸', short: 'SS', code: '+211' },
  { name: 'South Georgia', flag: '🇬🇸', short: 'GS', code: '+500' },
  { name: 'Spain', flag: '🇪🇸', short: 'ES', code: '+34' },
  { name: 'Sri Lanka', flag: '🇱🇰', short: 'LK', code: '+94' },
  { name: 'Sudan', flag: '🇸🇩', short: 'SD', code: '+249' },
  { name: 'Suriname', flag: '🇸🇷', short: 'SR', code: '+597' },
  { name: 'Svalbard', flag: '🇸🇯', short: 'SJ', code: '+47' },
  { name: 'Swaziland', flag: '🇸🇿', short: 'SZ', code: '+268' },
  { name: 'Sweden', flag: '🇸🇪', short: 'SE', code: '+46' },
  { name: 'Switzerland', flag: '🇨🇭', short: 'CH', code: '+41' },
  { name: 'Syria', flag: '🇸🇾', short: 'SY', code: '+963' },
  { name: 'Taiwan', flag: '🇹🇼', short: 'TW', code: '+886' },
  { name: 'Tajikistan', flag: '🇹🇯', short: 'TJ', code: '+992' },
  { name: 'Tanzania', flag: '🇹🇿', short: 'TZ', code: '+255' },
  { name: 'Thailand', flag: '🇹🇭', short: 'TH', code: '+66' },
  { name: 'Timor-Leste', flag: '🇹🇱', short: 'TL', code: '+670' },
  { name: 'Togo', flag: '🇹🇬', short: 'TG', code: '+228' },
  { name: 'Tokelau', flag: '🇹🇰', short: 'TK', code: '+690' },
  { name: 'Tonga', flag: '🇹🇴', short: 'TO', code: '+676' },
  { name: 'Trinidad & Tobago', flag: '🇹🇹', short: 'TT', code: '+1868' },
  { name: 'Tunisia', flag: '🇹🇳', short: 'TN', code: '+216' },
  { name: 'Turkey', flag: '🇹🇷', short: 'TR', code: '+90' },
  { name: 'Turkmenistan', flag: '🇹🇲', short: 'TM', code: '+993' },
  { name: 'Turks & Caicos Islands', flag: '🇹🇨', short: 'TC', code: '+1649' },
  { name: 'Tuvalu', flag: '🇹🇻', short: 'TV', code: '+688' },
  { name: 'Uganda', flag: '🇺🇬', short: 'UG', code: '+256' },
  { name: 'Ukraine', flag: '🇺🇦', short: 'UA', code: '+380' },
  { name: 'United Arab Emirates', flag: '🇦🇪', short: 'AE', code: '+971' },
  { name: 'United Kingdom', flag: '🇬🇧', short: 'GB', code: '+44' },
  { name: 'United States', flag: '🇺🇸', short: 'US', code: '+1' },
  { name: 'Uruguay', flag: '🇺🇾', short: 'UY', code: '+598' },
  { name: 'Uzbekistan', flag: '🇺🇿', short: 'UZ', code: '+998' },
  { name: 'Vanuatu', flag: '🇻🇺', short: 'VU', code: '+678' },
  { name: 'Venezuela', flag: '🇻🇪', short: 'VE', code: '+58' },
  { name: 'Vietnam', flag: '🇻🇳', short: 'VN', code: '+84' },
  { name: 'Virgin Islands, British', flag: '🇻🇬', short: 'VG', code: '+1284' },
  { name: 'Virgin Islands, U.S.', flag: '🇻🇮', short: 'VI', code: '+1340' },
  { name: 'Wallis & Futuna', flag: '🇼🇫', short: 'WF', code: '+681' },
  { name: 'Yemen', flag: '🇾🇪', short: 'YE', code: '+967' },
  { name: 'Zambia', flag: '🇿🇲', short: 'ZM', code: '+260' },
  { name: 'Zimbabwe', flag: '🇿🇼', short: 'ZW', code: '+263' }
];
